### PR TITLE
Fix incorrect configure option documentation.

### PR DESCRIPTION
**Pull request by svillemot**

### CODE REVIEW

**Comment by jjk-jacky** [comment]
whoops, good catch.
Applied, thanks!

**Comment by svillemot** [comment]
Just to clarify: you said "applied" but you did not merge the pull request. Am I missing something?

**Comment by svillemot** [comment]
Ok I see, it's because I should have created the PR against the next branch.

**Comment by jjk-jacky** [comment]
On Wed, 04 Jan 2017 04:20:51 -0800
Sébastien Villemot <notifications@github.com> wrote:

> Ok I see, it's because I should have created the PR against the next
> branch.

Possibly that, and also I think github likes actual merges, but I like
fast-forward better (cleaner history, IMHO), so it might not be "seen"
by github, but it is there yes.

**Comment by svillemot** [comment]
I personally think that actual merges are better. First, it keeps track of who did the merge and when. Second, it facilitates life for contributors like me: I had to reset my local copy before being able to create the 2nd pull request (instead of just doing a fast forward). Anyway, thanks for merging my commit.

**Pull request closed without merging**
